-- ============================================================================
-- SUPERSEDED · 적용하지 말 것.
--
--   초기 초안은 line_registrations 에 point_a/point_b 를 추가하려 했으나, 조인 설계 조사 결과
--   line_registrations 는 오픈 라인 생성의 마스터 SoT 가 아니며(cluster4_lines 에 line_registration_id
--   FK 없음), info 허브는 line_registrations 와 안정적 조인 키가 전혀 없다(활동타입 id ↔ IFBS 코드
--   불일치 · 브리지 미지원 · 현재 인덱스 위치 매칭뿐). 따라서 이 접근은 폐기.
--
--   → 대체: 2026-07-11_DRAFT_cluster4_line_point_configs.sql (오픈확인 config 식별자에 키잉하는
--     전용 config 테이블). 상세는 해당 파일 및 설계 보고 참조.
-- ============================================================================
-- (의도적으로 DDL 없음)
